export const mockProducts = [
  {
    id: 1,
    name: 'Sữa Tươi Vinamilk 1L',
    category: 'Sữa',
    originalPrice: 45000,
    salePrice: 35000,
    discount: 22,
    daysLeft: 5,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q1',
  },
  {
    id: 2,
    name: 'Bánh Mì Tươi Sandwich',
    category: 'Bánh',
    originalPrice: 25000,
    salePrice: 15000,
    discount: 40,
    daysLeft: 1,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q1',
  },
  {
    id: 3,
    name: 'Nước Cam Tropicana 1L',
    category: 'Nước Giải Khát',
    originalPrice: 38000,
    salePrice: 28000,
    discount: 26,
    daysLeft: 3,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q3',
  },
  {
    id: 4,
    name: 'Sữa Chua Hy Lạp 400g',
    category: 'Sữa Chua',
    originalPrice: 55000,
    salePrice: 42000,
    discount: 24,
    daysLeft: 2,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q5',
  },
  {
    id: 5,
    name: 'Phô Mai Con Bò Cười',
    category: 'Phô Mai',
    originalPrice: 32000,
    salePrice: 24000,
    discount: 25,
    daysLeft: 7,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q7',
  },
  {
    id: 6,
    name: 'Gạo ST25 5kg',
    category: 'Gạo',
    originalPrice: 180000,
    salePrice: 155000,
    discount: 14,
    daysLeft: 30,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q1',
  },
  {
    id: 7,
    name: 'Dầu Ăn Meizan 1L',
    category: 'Dầu Ăn',
    originalPrice: 42000,
    salePrice: 35000,
    discount: 17,
    daysLeft: 45,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q3',
  },
  {
    id: 8,
    name: 'Trứng Gà Ta Vissan 10 quả',
    category: 'Trứng',
    originalPrice: 38000,
    salePrice: 28000,
    discount: 26,
    daysLeft: 4,
    image: 'https://via.placeholder.com/150',
    store: 'BigMart Q5',
  },
];
