export const mockProducts = [
  {
    id: 1,
    name: 'Sua tuoi Vinamilk 1L',
    shop: 'VinMart',
    originalPrice: 25000,
    salePrice: 15000,
    discount: 40,
    daysLeft: 2,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 2,
    name: 'Banh mi sandwich',
    shop: 'Circle K',
    originalPrice: 20000,
    salePrice: 12000,
    discount: 40,
    daysLeft: 1,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 3,
    name: 'Yaourt Vinamilk 4 hop',
    shop: 'Coopmart',
    originalPrice: 30000,
    salePrice: 18000,
    discount: 40,
    daysLeft: 3,
    image: 'https://via.placeholder.com/150',
  },
  {
    id: 4,
    name: 'Banh quy Cosy goi 200g',
    shop: 'VinMart',
    originalPrice: 35000,
    salePrice: 21000,
    discount: 40,
    daysLeft: 2,
    image: 'https://via.placeholder.com/150',
  },
]